services:
    api:
        build:
            context: .
            dockerfile: src/finOps.Api/Dockerfile
        container_name: finops_api
        ports:
            - "8080:8080"
        depends_on:
            - database
            - cache
        env_file: .env.development

    database:
        image: postgres:17-alpine
        container_name: finops_postgres
        env_file: .env.development
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    cache:
        image: redis:8-alpine
        container_name: finops_redis
        ports:
            - "6379:6379"

volumes:
    postgres_data:
        driver: local
